version: "3.9"
services:
  mongo:
    container_name: "mongo"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: "always"
    volumes:
      - "mongo:/data/db"
  
  entity-studio-dashboard-service:
    container_name: "entity-studio-dashboard-service"
    image: "abc"
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
      HOST: "localhost"
      LOG_FILEPATH: "../log/studio-server.log"
      LOG_DIR: "./log"
      LOG_TIMESTAMP_FORMAT: "YYYY-MM-DD HH:mm:ss.SSS"
      LOG_LEVEL: "debug"
      DATABASE_FILEPATH: "../db/studio-server.db"
      DID_METHOD_NAME: "hs"
      JWT_SECRET: "00c2c433-a077-4e68-b19c-1234f014a510"
      STUDIO_SERVER_BASE_URL: "http://localhost:9000/"
      NODE_SERVER_BASE_URL: "http://localhost:5000/"
      NODE_SERVER_DID_CREATE_EP: "api/did/create_tmp"
      NODE_SERVER_SCHEMA_CREATE_EP: "api/schema/create"
      DB_URL: "mongodb://mongo:27017/studio-dashboard-service"
      PATH_TO_ISSUE_CRED: "api/v1/credential/walletAccepct"
      SSE_CLIENT_URL: "http://localhost:9001"
      WHITELISTED_CORS : '["http://localhost:9000","http://localhost:9001","http://192.168.29.12:9001", "https://localhost:9001", "http://192.168.29.209:9001", "http://entity.hypersign.id","https://entity.hypersign.id","http://localhost:9001", "https://wallet-stage.hypersign.id", "http://localhost:4999","192.168.29.13","http://localhost:1234","http://localhost:4000","https://wallet-jagrat.hypersign.id", "*"]'
      EMAIL_CREDENTITAL_SCHEMA_ID: "sch:hid:testnet:zufjU7LuQuJNFiUpuhCwYkTrakUu1VmtxE9SPi5TwfUB:1.0"
      HID_NETWORK_RPC: "https://rpc.jagrat.hypersign.id/"
      HID_NETWORK_API: "https://api.jagrat.hypersign.id/"
    depends_on:
      - "mongo"
volumes:
  mongo: {}
